import { FormState } from "./types.js";

export const categoryLabels: Record<string, string> = {
  bezerroLactente: "Bezerro(a) Lactente",
  bezerroDesmamado: "Bezerro(a) Desmamado(a)",
  novilha: "Novilha (8 a 24 meses)",
  vacaSolteira: "Vaca Solteira / Vazia",
  vacaParida: "Vaca Parida / Lactante",
  vacaGestanteSeca: "Vaca Gestante (Seca)",
  garroteRecria: "Garrote/Garrota",
  boiTerminacao: "Animal em Terminação",
  touro: "Touro",
};

// ---- Listas de opções reutilizáveis pelos blocos do formulário ----

// Bloco 03 — Raças (seleção múltipla)
export const breedOptions: string[] = [
  "Nelore",
  "Anelorado",
  "Guzerá",
  "Brahman",
  "Tabapuã",
  "Gir / Girolando",
  "Sindi",
  "Aberdeen Angus",
  "Brangus",
  "Senepol",
  "Bonsmara",
  "Hereford",
  "Canchim",
  "Simental",
  "Caracu",
  "Wagyu",
  "Cruzamento Industrial (F1)",
  "Outra",
];

// Bloco 04 — Destino principal da venda
export const destinoVendaOptions: string[] = [
  "Frigorífico",
  "Leilão",
  "Marchante",
  "Abate Próprio",
  "Misto",
  "Outro",
];

// Bloco 05A — Estado de degradação da pastagem
export const estadoPastagemOptions: string[] = [
  "Alto - >70%",
  "Moderado - entre 70% e 40%",
  "Baixo - <40%",
  "Misto - depende do piquete",
];

// Bloco 05A — Sistema de pastagem
export const sistemaPastejoOptions: string[] = [
  "Alternado",
  "Rotacionado",
  "Contínuo",
  "Diferido",
  "Híbrido",
];

// Bloco 05A — Método de controle de entrada/saída do pasto
export const metodoControlePastejoOptions: string[] = [
  "Régua de manejo de pasto",
  "Medição de altura do capim",
  "Percepção subjetiva do vaqueiro",
  "Rodízio por calendário fixo",
  "Não fazemos esse controle",
];

// Bloco 05A — Correção de solo e adubação
export const correcaoSoloOptions: string[] = [
  "Sim — anualmente / regularmente",
  "Sim — esporadicamente",
  "Não fazemos correção/adubação",
  "Não sei informar",
];

// Bloco 05A — Uso da vinhaça (subproduto do alambique de cachaça)
export const usoVinhacaOptions: string[] = [
  "Sim — na fertirrigação do pasto",
  "Sim — na alimentação animal",
  "Sim — fertirrigação e alimentação",
  "Não utilizamos vinhaça",
  "Não se aplica (sem alambique)",
];

// Bloco 08 — Vocação da propriedade
export const vocacaoOptions: string[] = [
  "Cria",
  "Recria",
  "Engorda / Terminação",
  "Ciclo completo (cria-recria-engorda)",
  "Pecuária mista / diversificada",
  "Em transição de modelo",
];

// Bloco 08 — Papel de uma eventual fábrica de ração
export const papelFabricaOptions: string[] = [
  "Reduzir o custo da alimentação",
  "Ganhar autonomia / verticalizar a nutrição",
  "Viabilizar confinamento / semi-confinamento",
  "Aproveitar subprodutos locais (bagaço, vinhaça)",
  "Ainda estamos avaliando",
];

// Bloco 08 — Categoria prioritária para a produção de ração
export const categoriaPrioritariaOptions: string[] = [
  "Animais em terminação",
  "Garrotes/Garrotas em recria",
  "Vacas paridas / lactantes",
  "Novilhas de reposição",
  "Todas as categorias igualmente",
  "Ainda não definido",
];

// Estrutura de plantel zerada (formulário em branco para os funcionários)
const emptyHerd = {
  bezerroLactente: { heads: 0, weight: 0, imsCoef: 1.5 },
  bezerroDesmamado: { heads: 0, weight: 0, imsCoef: 2.2 },
  novilha: { heads: 0, weight: 0, imsCoef: 2.0 },
  vacaSolteira: { heads: 0, weight: 0, imsCoef: 2.0 },
  vacaParida: { heads: 0, weight: 0, imsCoef: 2.5 },
  vacaGestanteSeca: { heads: 0, weight: 0, imsCoef: 1.8 },
  garroteRecria: { heads: 0, weight: 0, imsCoef: 2.0 },
  boiTerminacao: { heads: 0, weight: 0, imsCoef: 2.2 },
  touro: { heads: 0, weight: 0, imsCoef: 1.8 },
};

const emptyEquip = { possui: false, status: "Inexistente", capacidade: "", obs: "" };

// Formulário EM BRANCO — estado inicial entregue ao usuário final.
export const emptyFormState: FormState = {
  nomeProdutor: "",
  contatoZap: "",
  email: "",
  cargo: "",
  cidade: "",
  obsPrevia: "",
  rotinaPratica: "",
  herd: { ...emptyHerd },
  extraCatName: "",
  extraCatHeads: 0,
  extraCatWeight: 0,
  extraCatImsCoef: 2.0,
  extraCategories: [],
  rotinaControle: "",
  bezerroDesmGmd: 0,
  novilhaGmd: 0,
  garroteGmd: 0,
  boiGmd: 0,
  vacaGmd: 0,
  gmdMedido: "estimativa",
  pesoEntrada: 0,
  pesoAlvo: 0,
  rendimentoCarcaça: 0,
  tempoAprov: 0,
  racaPredominante: "",
  racas: [],
  animaisVendidosAnual: 0,
  rotinaDesempenho: "",
  precoArroba: 0,
  destinoPrincipal: "",
  destinoPrincipalOutro: "",
  contrato: "",
  descontoMedio: 0,
  freteMedio: 0,
  outrosCustos: 0,
  custoComercializacao: 0,
  sazonalidade: [],
  metaReceitaAnual: 0,
  rotinaComercial: "",
  areaTotalPastagem: 0,
  especiePredominantePastagem: "",
  estadoMedioPastagem: "",
  producaoEstimadaPastagem: "",
  sistemaPastejo: "",
  metodoControlePastejo: "",
  correcaoSoloAdubacao: "",
  usoVinhaca: "",
  custoVinhacaHa: 0,
  pragasComuns: "",
  tecnicasManejo: "",
  capimTipo: "",
  numPiquetes: 0,
  tamanhoMedioPiqueteHa: 0,
  infoPiquetes: "",
  adubacaoPastagem: false,
  custoMensalPastagem: 0,
  volumosos: [],
  volumeMesVolumoso: 0,
  custoVolumoso: 0,
  dispBagacoVinhaca: "",
  vinhacaUtilizada: "",
  suplementos: [],
  planejamentoSuplemento: "",
  volumeSuplMes: 0,
  custoSuplemento: 0,
  fornecedorSuplemento: "",
  distanciaFornecedor: 0,
  frequenciaFornecimento: "",
  rotinaAlimentacao: "",
  responsavelDieta: "",
  custoNaoAlimentacao: 0,
  maoDeObraDireta: 0,
  sanidade: 0,
  manutencaoEquip: 0,
  custoExtra: 0,
  descCustoExtra: "",
  rotinaCustos: "",
  equipments: {
    balancaTronco: { ...emptyEquip },
    forrageira: { ...emptyEquip },
    misturador: { ...emptyEquip },
    moinho: { ...emptyEquip },
    trator: { ...emptyEquip },
    deposito: { ...emptyEquip },
    balancaPesagem: { ...emptyEquip },
    bombaTransferencia: { ...emptyEquip },
  },
  terrenoDisponivel: "Sim - Há galpão e terreno plano",
  energiaTrifasica: "Não sei",
  distanciaCurral: 0,
  rotinaInfra: "",
  metaSurgimento24: 0,
  metaSurgimento36: 0,
  confinamentoFuturo: "a_avaliar",
  categoriaPrioritaria: "Ainda não definido",
  vocacaoPropriedade: "",
  papelFabricaRacao: "",
  visaoProprietario: "",
  visaoGerente: "",
  visaoOperacional: "",
  visaoAdministrativa: "",
  capexOrcamento: 0,
  paybackMeta: "",
  restricaoProcesso: "",
  expectativasGerais: "",
  contextoReal: "",
};

// Estado de DEMONSTRAÇÃO com dados fictícios — usado apenas para testes/validação.
export const defaultFormState: FormState = {
  nomeProdutor: "Rodrigo Silva de Alencar",
  contatoZap: "(84) 99876-5432",
  email: "rodrigo.alencar@agrobrazil.com.br",
  cargo: "Gerente de Pecuária",
  cidade: "Nísia Floresta - RN",
  obsPrevia: "",
  rotinaPratica: "",
  herd: {
    bezerroLactente: { heads: 40, weight: 75, imsCoef: 1.5 },
    bezerroDesmamado: { heads: 50, weight: 160, imsCoef: 2.2 },
    novilha: { heads: 55, weight: 260, imsCoef: 2.0 },
    vacaSolteira: { heads: 25, weight: 450, imsCoef: 2.0 },
    vacaParida: { heads: 70, weight: 480, imsCoef: 2.5 },
    vacaGestanteSeca: { heads: 35, weight: 510, imsCoef: 1.8 },
    garroteRecria: { heads: 60, weight: 320, imsCoef: 2.0 },
    boiTerminacao: { heads: 110, weight: 430, imsCoef: 2.2 },
    touro: { heads: 3, weight: 750, imsCoef: 1.8 },
  },
  extraCatName: "",
  extraCatHeads: 0,
  extraCatWeight: 0,
  extraCatImsCoef: 2.0,
  extraCategories: [
    { name: "Vacas de Descarte", heads: 12, weight: 460, imsCoef: 2.0 },
  ],
  rotinaControle: "Apontamentos no caderno de curral e planilha Excel simples na sede.",
  bezerroDesmGmd: 0.65,
  novilhaGmd: 0.5,
  garroteGmd: 0.7,
  boiGmd: 1.15,
  vacaGmd: 0.18,
  gmdMedido: "estimativa",
  pesoEntrada: 300,
  pesoAlvo: 535,
  rendimentoCarcaça: 53.0,
  tempoAprov: 110,
  racaPredominante: "",
  racas: ["Nelore", "Cruzamento Industrial (F1)", "Aberdeen Angus"],
  animaisVendidosAnual: 125,
  rotinaDesempenho: "Pesagem de entrada do confinamento e peso de balança na saída para o frigorífico.",
  precoArroba: 282.0,
  destinoPrincipal: "Frigorífico",
  destinoPrincipalOutro: "",
  contrato: "Nenhum (Venda no spot direto)",
  descontoMedio: 1.5,
  freteMedio: 10.0,
  outrosCustos: 3.5,
  custoComercializacao: 18.5,
  sazonalidade: ["Ago", "Set", "Out", "Nov", "Dez"],
  metaReceitaAnual: 450000,
  rotinaComercial: "Cotação semanal direta por telefone e WhatsApp com corretores potiguares.",
  areaTotalPastagem: 140,
  especiePredominantePastagem: "Brachiaria decumbens e Capim Marandu",
  estadoMedioPastagem: "Moderado - entre 70% e 40%",
  producaoEstimadaPastagem: "Déficit de pasto nos meses secos (Agosto a Janeiro).",
  sistemaPastejo: "Rotacionado",
  metodoControlePastejo: "Percepção subjetiva do vaqueiro",
  correcaoSoloAdubacao: "Sim — esporadicamente",
  usoVinhaca: "Sim — na fertirrigação do pasto",
  custoVinhacaHa: 120,
  pragasComuns: "Cigarrinha-das-pastagens e formiga cortadeira",
  tecnicasManejo: "Vedação de piquetes no início das chuvas",
  capimTipo: "",
  numPiquetes: 6,
  tamanhoMedioPiqueteHa: 8,
  infoPiquetes: "6 piquetes de ~8 ha; rodízio a cada 3 dias com 30 de descanso.",
  adubacaoPastagem: false,
  custoMensalPastagem: 3500,
  volumosos: ["silagem_milho", "cana_picada"],
  volumeMesVolumoso: 90,
  custoVolumoso: 14500,
  dispBagacoVinhaca: "Sim, usinas a 30 km fornecem bagaço de cana no inverno.",
  vinhacaUtilizada: "Não",
  suplementos: ["sal_proteico", "milho_moido", "farelo_soja"],
  planejamentoSuplemento: "Hoje dependemos de ração ensacada comercial; o gargalo é o custo por saca na seca e a falta de padronização da dosagem no cocho. A ideia da fábrica própria nasceu para reduzir esse custo e ganhar autonomia.",
  volumeSuplMes: 15,
  custoSuplemento: 28000,
  fornecedorSuplemento: "NutriNordeste e distribuidores em Parnamirim/RN",
  distanciaFornecedor: 35,
  frequenciaFornecimento: "Quinzenal",
  rotinaAlimentacao: "Trator puxa a ração misturada na pá para os cochos, duas vezes ao dia.",
  responsavelDieta: "Não há profissional; o próprio gerente define no empírico.",
  custoNaoAlimentacao: 4500,
  maoDeObraDireta: 8800,
  sanidade: 2800,
  manutencaoEquip: 1500,
  custoExtra: 2000,
  descCustoExtra: "Combustível do trator e energia elétrica da sede.",
  rotinaCustos: "Apurado semestralmente somando notas fiscais na contabilidade.",
  equipments: {
    balancaTronco: { possui: true, status: "Operando parcialmente", capacidade: "1500 kg", obs: "Necessita calibração das células." },
    forrageira: { possui: true, status: "Operando plenamente", capacidade: "Nogueira DPM-4 de 7.5 CV", obs: "Fixada em base de concreto." },
    misturador: { possui: false, status: "Inexistente", capacidade: "", obs: "Planejando adquirir o primeiro misturador." },
    moinho: { possui: true, status: "Operando parcialmente", capacidade: "600 kg/h", obs: "Martelos um pouco gastos." },
    trator: { possui: true, status: "Operando parcialmente", capacidade: "Valtra 85 CV", obs: "Bomba hidráulica com chiado leve." },
    deposito: { possui: true, status: "Operando plenamente", capacidade: "Galpão alvenaria 100m²", obs: "Coberto, seco." },
    balancaPesagem: { possui: false, status: "Inexistente", capacidade: "", obs: "Sem balança de fluxo." },
    bombaTransferencia: { possui: false, status: "Inexistente", capacidade: "", obs: "Fornecimento manual de ureia." },
  },
  terrenoDisponivel: "Sim - Há galpão e terreno plano",
  energiaTrifasica: "Sim",
  distanciaCurral: 50,
  rotinaInfra: "Manutenção corretiva pelo mecânico local.",
  metaSurgimento24: 550,
  metaSurgimento36: 750,
  confinamentoFuturo: "sim_semi",
  categoriaPrioritaria: "Animais em terminação",
  vocacaoPropriedade: "Ciclo completo (cria-recria-engorda)",
  papelFabricaRacao: "Ganhar autonomia / verticalizar a nutrição",
  visaoProprietario: "Reduzir a dependência de ração ensacada e ganhar margem por arroba.",
  visaoGerente: "Padronizar a dieta e ter previsibilidade de custo mensal.",
  visaoOperacional: "Facilitar a lida diária e reduzir o esforço de mistura manual.",
  visaoAdministrativa: "Organizar as compras de insumo e o fluxo de caixa.",
  capexOrcamento: 110000,
  paybackMeta: "12 a 18 meses",
  restricaoProcesso: "Receio dos peões com a dosagem exata de ureia no cocho.",
  expectativasGerais: "Cortar a dependência de rações comerciais ensacadas e moer milho próprio.",
  contextoReal: "Operação familiar em transição; pastagem arenosa exige volumoso de cocho na seca.",
};

// ===================== ACOMPANHAMENTO MENSAL =====================
import { MonthlyFormState, MonthlyCategory } from "./types.js";

export const monthlyCategoryLabels: Record<string, string> = {
  aleitamento: "Bezerros(as) em Aleitamento (cria)",
  desmamados: "Bezerros(as) Desmamados(as)",
  recria: "Recria (Garrotes/Garrotas)",
  engordaTerminacao: "Engorda / Terminação",
  vacasCria: "Vacas de Cria (Matrizes)",
  reprodutores: "Reprodutores (Touros)",
  resguardoEnfermaria: "Resguardo / Enfermaria",
};

export const condicaoPastoOptions: string[] = [
  "Excelente — pasto cheio e vigoroso",
  "Bom — oferta adequada",
  "Regular — começando a faltar",
  "Ruim — déficit de forragem",
  "Crítico — pasto esgotado",
];

const emptyCat = (): MonthlyCategory => ({
  inicio: 0, nascimentos: 0, mortes: 0, compras: 0, vendas: 0,
  transferencias: 0, pesoMedioAnterior: 0, pesoMedioAtual: 0,
});

const buildCats = (filler?: Partial<Record<string, MonthlyCategory>>): Record<string, MonthlyCategory> => {
  const obj: Record<string, MonthlyCategory> = {};
  Object.keys(monthlyCategoryLabels).forEach((k) => { obj[k] = (filler && filler[k]) ? filler[k]! : emptyCat(); });
  return obj;
};

// Formulário mensal EM BRANCO (estado inicial entregue ao responsável)
export const emptyMonthlyState: MonthlyFormState = {
  mesReferencia: "",
  dataPreenchimento: "",
  responsavelNome: "",
  responsavelCargo: "",
  categorias: buildCats(),
  doencasOcorridas: "",
  numAnimaisDoentes: 0,
  acidentes: "",
  mortesCausas: "",
  vacinacoesVermifugacoes: "",
  prevencaoSazonal: "",
  condicaoPasto: "",
  alturaPastoCm: 0,
  metodoManejoPasto: "",
  controleEntradaSaida: "",
  piquetesUso: 0,
  piquetesDescanso: 0,
  pluviometriaMm: 0,
  pragasInvasoras: "",
  correcaoAdubacao: "",
  volumosoTipo: "",
  volumosoQtdTonMes: 0,
  volumosoCustoMes: 0,
  suplementoTipo: "",
  suplementoQtdTonMes: 0,
  suplementoCustoMes: 0,
  mudancasDieta: "",
  comprasNum: 0,
  comprasPesoMedio: 0,
  comprasValorTotal: 0,
  vendasNum: 0,
  vendasArrobasTotal: 0,
  vendasValorTotal: 0,
  vendasCustoComercializacao: 0,
  custoMaoDeObra: 0,
  custoSanidade: 0,
  custoInsumos: 0,
  custoOutros: 0,
  observacoesGargalos: "",
};

// Estado de DEMONSTRAÇÃO com dados fictícios — usado apenas para testes/validação.
export const demoMonthlyState: MonthlyFormState = {
  mesReferencia: "Maio/2026",
  dataPreenchimento: "2026-05-31",
  responsavelNome: "José Carlos Ferreira",
  responsavelCargo: "Gerente de Manejo",
  categorias: buildCats({
    aleitamento: { inicio: 40, nascimentos: 8, mortes: 1, compras: 0, vendas: 0, transferencias: -6, pesoMedioAnterior: 70, pesoMedioAtual: 88 },
    desmamados: { inicio: 50, nascimentos: 0, mortes: 0, compras: 0, vendas: 0, transferencias: 6, pesoMedioAnterior: 155, pesoMedioAtual: 172 },
    recria: { inicio: 60, nascimentos: 0, mortes: 1, compras: 0, vendas: 0, transferencias: 0, pesoMedioAnterior: 310, pesoMedioAtual: 332 },
    engordaTerminacao: { inicio: 110, nascimentos: 0, mortes: 0, compras: 0, vendas: 20, transferencias: 0, pesoMedioAnterior: 410, pesoMedioAtual: 445 },
    vacasCria: { inicio: 130, nascimentos: 0, mortes: 1, compras: 0, vendas: 3, transferencias: 0, pesoMedioAnterior: 475, pesoMedioAtual: 470 },
    reprodutores: { inicio: 3, nascimentos: 0, mortes: 0, compras: 0, vendas: 0, transferencias: 0, pesoMedioAnterior: 750, pesoMedioAtual: 752 },
    resguardoEnfermaria: { inicio: 2, nascimentos: 0, mortes: 0, compras: 0, vendas: 0, transferencias: 0, pesoMedioAnterior: 380, pesoMedioAtual: 392 },
  }),
  doencasOcorridas: "3 casos de miíase (bicheira) e 2 de tristeza parasitária bovina.",
  numAnimaisDoentes: 5,
  acidentes: "1 garrote com corte em cerca, tratado no local.",
  mortesCausas: "1 bezerro (diarreia neonatal), 1 garrote (acidente), 1 vaca (parto distócico).",
  vacinacoesVermifugacoes: "Vermifugação estratégica de toda a recria; reforço de clostridioses nos bezerros.",
  prevencaoSazonal: "Controle de mosca-do-chifre e carrapato no início das chuvas.",
  condicaoPasto: "Bom — oferta adequada",
  alturaPastoCm: 28,
  metodoManejoPasto: "Rotacionado",
  controleEntradaSaida: "Régua de manejo de pasto",
  piquetesUso: 4,
  piquetesDescanso: 2,
  pluviometriaMm: 95,
  pragasInvasoras: "Cigarrinha-das-pastagens em dois piquetes.",
  correcaoAdubacao: "Adubação nitrogenada de cobertura em 12 ha.",
  volumosoTipo: "Silagem de milho",
  volumosoQtdTonMes: 90,
  volumosoCustoMes: 14500,
  suplementoTipo: "Proteinado + milho moído",
  suplementoQtdTonMes: 15,
  suplementoCustoMes: 28000,
  mudancasDieta: "Aumento do concentrado para o lote de terminação que será vendido.",
  comprasNum: 0,
  comprasPesoMedio: 0,
  comprasValorTotal: 0,
  vendasNum: 23,
  vendasArrobasTotal: 322,
  vendasValorTotal: 90804,
  vendasCustoComercializacao: 4255,
  custoMaoDeObra: 8800,
  custoSanidade: 2800,
  custoInsumos: 3500,
  custoOutros: 2000,
  observacoesGargalos: "Déficit de pasto previsto para os próximos meses secos; precisamos antecipar a compra de volumoso.",
};
