import { FormState } from "./types.js";

export const categoryLabels: Record<string, string> = {
  bezerroLactente: "Bezerro(a) Lactente",
  bezerroDesmamado: "Bezerro(a) Desmamado(a)",
  novilha: "Novilha (8 a 24 meses)",
  vacaSolteira: "Vaca Solteira / Vazia",
  vacaParida: "Vaca Parida / Lactante",
  vacaGestanteSeca: "Vaca Gestante (Seca)",
  garroteRecria: "Garrote em Recria",
  boiTerminacao: "Boi em Terminação",
  touro: "Touro",
};

export const defaultFormState: FormState = {
  nomeProdutor: "Rodrigo Silva de Alencar",
  contatoZap: "(84) 99876-5432",
  email: "rodrigo.alencar@agrobrazil.com.br",
  cargo: "Gerente de Pecuária",
  cidade: "Nísia Floresta - RN",
  obsPrevia: "Estamos estruturando a transição para semi-confinamento de bois e queremos verticalizar a nossa nutrição local.",
  rotinaPratica: "A mistura de concentrados hoje é puramente manual na pá de pedreiro ou betoneira, sem pesagem eletrônica.",
  herd: {
    bezerroLactente: { heads: 40, weight: 75, imsCoef: 1.5 },
    bezerroDesmamado: { heads: 50, weight: 160, imsCoef: 2.2 },
    novilha: { heads: 55, weight: 260, imsCoef: 2.0 },
    vacaSolteira: { heads: 25, weight: 450, imsCoef: 2.0 },
    vacaParida: { heads: 70, weight: 480, imsCoef: 2.8 },
    vacaGestanteSeca: { heads: 35, weight: 510, imsCoef: 1.8 },
    garroteRecria: { heads: 60, weight: 320, imsCoef: 2.0 },
    boiTerminacao: { heads: 110, weight: 430, imsCoef: 2.2 },
    touro: { heads: 3, weight: 750, imsCoef: 1.8 },
  },
  extraCatName: "",
  extraCatHeads: 0,
  extraCatWeight: 0,
  extraCatImsCoef: 2.0,
  rotinaControle: "Apontamentos no caderninho de curral e planilha Excel simples no computador da sede.",
  bezerroDesmGmd: 0.65,
  novilhaGmd: 0.50,
  garroteGmd: 0.70,
  boiGmd: 1.15,
  vacaGmd: 0.18,
  gmdMedido: "estimativa",
  pesoEntrada: 300,
  pesoAlvo: 535,
  rendimentoCarcaça: 53.0,
  tempoAprov: 110,
  racaPredominante: "Nelore e Cruzamento Industrial (Angus)",
  animaisVendidosAnual: 125,
  rotinaDesempenho: "Apenas pesagem de entrada do confinamento e o peso de balança na saída oficial do frigorífico local.",
  precoArroba: 282.0,
  destinoPrincipal: "Frigorífico Potiguar Alimentos S/A",
  contrato: "Nenhum (Venda no spot direto)",
  descontoMedio: 1.5,
  freteMedio: 10.0,
  outrosCustos: 3.5,
  sazonalidade: ["Ago", "Set", "Out", "Nov", "Dez"],
  metaReceitaAnual: 450000,
  rotinaComercial: "Cotação semanal direta por telefone e WhatsApp com corretores de gado potiguares.",
  areaTotalPastagem: 140,
  especiePredominantePastagem: "Brachiaria decumbens e Capim Marandu alternados",
  estadoMedioPastagem: "Pasto arenoso moderadamente degradado (Nísia Floresta RN possui solo muito arenoso)",
  producaoEstimadaPastagem: "Déficit absurdo de pasto nos meses secos (Agosto a Janeiro), necessitando volumoso de cocho",
  sistemaPastejo: "Rotacionado estático",
  numPiquetes: 6,
  adubacaoPastagem: false,
  custoMensalPastagem: 3500,
  volumosos: ["silagem_milho", "cana_picada"],
  volumeMesVolumoso: 90,
  custoVolumoso: 14500,
  dispBagacoVinhaca: "Sim, usinas a 30 km fornecem bagaço de cana no inverno sob agendamento",
  vinhacaUtilizada: "Não",
  suplementos: ["sal_proteico", "milho_moido", "soja"],
  volumeSuplMes: 15,
  custoSuplemento: 28000,
  fornecedorSuplemento: "NutriNordeste e distribuidores em Parnamirim/RN",
  distanciaFornecedor: 35,
  frequenciaFornecimento: "Quinzenal",
  rotinaAlimentacao: "O cavalo ou trator puxa a ração misturada na pá na carretinha de madeira para os cochos, duas vezes ao dia.",
  custoNaoAlimentacao: 4500,
  maoDeObraDireta: 8800,
  sanidade: 2800,
  manutencaoEquip: 1500,
  custoExtra: 2000,
  descCustoExtra: "Combustível para o trator e energia elétrica residencial da sede",
  rotinaCustos: "Apurado de forma semestral somando notas fiscais na contabilidade.",
  equipments: {
    balancaTronco: { possui: true, status: "Mapeado", capacidade: "1500 kg", obs: "Necessita calibração rápida nas células Potiguar" },
    forrageira: { possui: true, status: "Excelente", capacidade: "Nogueira DPM-4 de 7.5 CV", obs: "Instalado fixado em base de concreto" },
    misturador: { possui: false, status: "Inexistente", capacidade: "Nenhuma", obs: "Planejando adquirir o primeiro misturador para economia real" },
    moinho: { possui: true, status: "Mapeado", capacidade: "600 kg/h", obs: "Martelos um pouco gastos" },
    trator: { possui: true, status: "Mapeado", capacidade: "Valtra 85 CV antigo", obs: "Bomba hidráulica apresentando chiado leve" },
    deposito: { possui: true, status: "Excelente", capacidade: "Galpão alvenaria 100m²", obs: "Coberto com telhas de fibrocimento, seco" },
    balancaPesagem: { possui: false, status: "Inexistente", capacidade: "Nenhuma", obs: "Sem balança de fluxo ou ensacadora mecânica" },
    bombaTransferencia: { possui: false, status: "Inexistente", capacidade: "Nenhuma", obs: "Fornecimento manual de ureia diluída" },
  },
  terrenoDisponivel: "Sim - Há uma área plana limpa de 300m² anexa ao galpão principal de guarda",
  energiaTrifasica: "Sim",
  distanciaCurral: 50,
  rotinaInfra: "Manutenção sob quebra corretiva pelo mecânico local de Nísia Floresta.",
  metaSurgimento24: 550,
  metaSurgimento36: 750,
  confinamentoFuturo: "sim_semi",
  categoriaPrioritaria: "Boi em terminação e Novilhas recriadas",
  capexOrcamento: 110000,
  paybackMeta: "12 a 18 meses",
  restricaoProcesso: "Peões tradicionais com receio de dosagem exata de ureia de cocho, gerando medo de intoxicação e atraso operacional.",
  expectativasGerais: "Cortar totalmente a dependência de rações concentradas comerciais ensacadas. Queremos comprar milho a granel, moer e misturar núcleo próprio.",
};
